//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\localDatabase" +
            ".mdf;Integrated Security=True;Connect Timeout=30")]
        public string localDatabase {
            get {
                return ((string)(this["localDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=D:\\INF\\ARTURDZIUBICH01.12.2020" +
            "\\ARTURDZIUBICH01.12.2020\\LOCALDATABASE.MDF;Integrated Security=True;Connect Time" +
            "out=30;Encrypt=False;TrustServerCertificate=False")]
        public string D__INF_ARTURDZIUBICH01_12_2020_ARTURDZIUBICH01_12_2020_LOCALDATABASE_MDFConnectionString {
            get {
                return ((string)(this["D__INF_ARTURDZIUBICH01_12_2020_ARTURDZIUBICH01_12_2020_LOCALDATABASE_MDFConnectio" +
                    "nString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=D:\\INF\\ARTURDZIUBICH01.12.2020" +
            "\\ARTURDZIUBICH01.12.2020\\BIN\\DEBUG\\LOCALDATABASE.MDF;Integrated Security=True;Co" +
            "nnect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string D__INF_ARTURDZIUBICH01_12_2020_ARTURDZIUBICH01_12_2020_BIN_DEBUG_LOCALDATABASE_MDFConnectionString {
            get {
                return ((string)(this["D__INF_ARTURDZIUBICH01_12_2020_ARTURDZIUBICH01_12_2020_BIN_DEBUG_LOCALDATABASE_MD" +
                    "FConnectionString"]));
            }
        }
    }
}
